// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the MyFirstModule module
	public static void aCT_Location_NewLocationOnly(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.ACT_Location_NewLocationOnly").withParams(params).execute(context);
	}
	public static void oCh_Location_LocationSet(IContext context, myfirstmodule.proxies.Location _location)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Location", _location == null ? null : _location.getMendixObject());
		Core.microflowCall("MyFirstModule.OCh_Location_LocationSet").withParams(params).execute(context);
	}
}