// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the MyFirstModule module

	public static void aCT_Location_NewLocationOnly(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "MyFirstModule.ACT_Location_NewLocationOnly", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void oCh_Location_LocationSet(IContext context, myfirstmodule.proxies.Location _location)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Location", _location == null ? null : _location.getMendixObject());
			Core.execute(context, "MyFirstModule.OCh_Location_LocationSet", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}